[package]
name = "block_chain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
ring = "0.17.11"
serde_json = "1.0.140"
chrono = "0.4.40"
rand = "0.9.0"
hex = "0.4.3"
